// Golden-snapshot reproduction (§10, §26.16). These files were generated by the
// approved implementation ONLY after the formula/invariant tests passed, and are
// never hand-edited. Future code must reproduce them exactly unless model_version
// changes. A snapshot test alone is not sufficient — the formula-level tests in
// the sibling files prove the snapshots were not produced by broken logic.

import { describe, expect, it } from 'vitest';
import { evaluateWideReceiver } from '@/wr-model/engine';
import { PRIMARY_FIXTURES, loadExpected, loadFixture } from '@/wr-model/testutil';

describe('golden snapshots reproduce exactly', () => {
  for (const name of PRIMARY_FIXTURES) {
    it(name, () => {
      const output = evaluateWideReceiver(loadFixture(name));
      const expected = loadExpected(name);
      expect(output).toEqual(expected);
    });
  }
});
