import type { TEMVPInput } from "../../src/te-model/types.js";

/**
 * Fully-specified, fallback-free, healthy baseline TE used by formula tests.
 * Fictional player; values are chosen to sit inside every reference range.
 */
export function baseInput(overrides: Partial<TEMVPInput> = {}): TEMVPInput {
  const base: TEMVPInput = {
    player_id: "TE-TEST-BASE",
    player_name: "Baseline Test Player",
    team: "TST",
    age: 26,
    nfl_seasons_completed: 4,
    draft_round: 2,
    prospect_type: "BALANCED",
    career_routes: 1500,
    career_targets: 320,
    route_participation_last4: 0.7,
    route_participation_last8: 0.68,
    snap_share_last4: 0.8,
    targets_per_route_run: 0.18,
    target_share: 0.14,
    average_depth_of_target: 7.5,
    red_zone_target_rate: 0.2,
    end_zone_target_rate: 0.09,
    catchable_target_rate: 0.84,
    catch_rate: 0.7,
    yards_per_target: 7.6,
    yards_per_reception: 10.9,
    yac_per_reception: 4.9,
    projected_team_dropbacks: 35,
    team_points_per_drive: 2.0,
    team_red_zone_trips_per_game: 3.3,
    qb_environment_score: 65,
    competition_pressure: 0.4,
    contract_security: 0.7,
    depth_chart_role: "TE1",
    role_change: "STABLE",
    coaching_continuity: "CONTINUITY",
    teammate_return_flag: false,
    another_receiving_te_flag: false,
    temporary_opportunity_flag: false,
    new_team_flag: false,
    injury_status: "HEALTHY",
    practice_status: "FULL",
    expected_games_remaining: 8,
    workload_ramp_factor: 1.0,
    previous_route_participation: 0.68,
    previous_targets_per_route_run: 0.18,
    career_targets_per_route_run: 0.18,
    career_catch_rate: 0.69,
    career_yards_per_target: 7.5,
    career_yards_per_reception: 10.8,
    career_yac_per_reception: 4.8,
    career_red_zone_target_rate: 0.19,
    career_end_zone_target_rate: 0.08,
    as_of_timestamp: "2025-11-05T12:00:00Z",
  };
  return { ...base, ...overrides };
}

/** Input with every nullable fallback-supported field null (missing-data profile). */
export function missingDataInput(overrides: Partial<TEMVPInput> = {}): TEMVPInput {
  return baseInput({
    player_id: "TE-TEST-MISSING",
    player_name: "Missing Data Test Player",
    team: null,
    draft_round: null,
    prospect_type: "UNKNOWN",
    career_routes: 40,
    career_targets: 10,
    route_participation_last4: null,
    route_participation_last8: null,
    snap_share_last4: null,
    targets_per_route_run: null,
    target_share: null,
    average_depth_of_target: null,
    red_zone_target_rate: null,
    end_zone_target_rate: null,
    catchable_target_rate: null,
    catch_rate: null,
    yards_per_target: null,
    yards_per_reception: null,
    yac_per_reception: null,
    projected_team_dropbacks: null,
    team_points_per_drive: null,
    team_red_zone_trips_per_game: null,
    qb_environment_score: null,
    competition_pressure: null,
    contract_security: null,
    depth_chart_role: "UNKNOWN",
    role_change: "UNKNOWN",
    coaching_continuity: "UNKNOWN",
    injury_status: "UNKNOWN",
    practice_status: "UNKNOWN",
    workload_ramp_factor: null,
    previous_route_participation: null,
    previous_targets_per_route_run: null,
    career_targets_per_route_run: null,
    career_catch_rate: null,
    career_yards_per_target: null,
    career_yards_per_reception: null,
    career_yac_per_reception: null,
    career_red_zone_target_rate: null,
    career_end_zone_target_rate: null,
    ...overrides,
  });
}
