// Golden-snapshot reproduction (§26.16.11). These files were generated by the
// approved implementation ONLY after the formula/invariant tests passed, and are
// never hand-edited. Future code must reproduce them exactly unless model_version
// or reference_version changes. The sibling formula-level tests prove the
// snapshots were not produced by broken logic.

import { describe, expect, it } from 'vitest';
import { evaluateRunningBack } from '@/rb-model/engine';
import { PRIMARY_FIXTURES, loadExpected, loadFixture } from '@/rb-model/testutil';

describe('golden snapshots reproduce exactly', () => {
  for (const name of PRIMARY_FIXTURES) {
    it(name, () => {
      const output = evaluateRunningBack(loadFixture(name));
      const expected = loadExpected(name);
      expect(output).toEqual(expected);
    });
  }
});
