import { useMemo } from 'react';
import { Link } from 'react-router-dom';
import { marketData } from '@/services/marketData/mock/MockMarketDataService';
import { useAppStore } from '@/store/useAppStore';
import { FORMATS } from '@/config/market';
import { fmtDate } from '@/lib/format';
import { Tape } from '@/components/market/Tape';
import { MarketMoversPanel } from '@/components/market/rows';
import { FormatRibbon } from '@/components/chrome/FormatRibbon';
import { DataFreshnessBadge, ConfidencePill } from '@/components/chrome/Honesty';
import { Footer } from '@/components/chrome/Footer';
import { WatchlistStrip } from '@/components/market/WatchlistStrip';

export default function MarketPage() {
  const format = useAppStore((s) => s.format);
  const date = marketData.getMarketDate();
  const board = useMemo(() => marketData.getBoard(format), [format]);
  const movers = useMemo(() => marketData.getMovers(format), [format]);
  const lastUpdated = date + 'T06:00:00Z';

  return (
    <div className="space-y-5">
      {/* Market header — the "market open" ritual (§18.2) */}
      <header className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 text-2xl font-bold text-text-primary">
            <span className="relative flex h-2.5 w-2.5">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-up/60" />
              <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-up" />
            </span>
            Market Update
          </h1>
          <p className="text-sm text-text-secondary">
            {fmtDate(date)} · close 06:00 UTC · {FORMATS[format].label}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <ConfidencePill confidence="medium" />
          <DataFreshnessBadge lastUpdated={lastUpdated} />
          <FormatRibbon compact />
        </div>
      </header>

      <Tape rows={board} />

      <WatchlistStrip />

      {/* Movers grid */}
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
        <MarketMoversPanel title="Biggest Risers" subtitle="Top 24-hour gains" rows={movers.risers} metric="d1" accent="up" viewAllHref="/board?sort=d1" />
        <MarketMoversPanel title="Biggest Fallers" subtitle="Top 24-hour drops" rows={movers.fallers} metric="d1" accent="down" viewAllHref="/board?sort=d30" />
        <MarketMoversPanel title="Buy-Low Windows" subtitle="Undervalued after a 30-day dip" rows={movers.buyLow} metric="d30" accent="up" viewAllHref="/board?tag=buy_low_window&sort=mis" emptyNote="No buy-low windows in this format today." />
        <MarketMoversPanel title="Sell-High Warnings" subtitle="Overvalued after a 30-day run" rows={movers.sellHigh} metric="d30" accent="down" viewAllHref="/board?sort=misAsc" emptyNote="No sell-high warnings today." />
        <MarketMoversPanel title="Overheated Assets" subtitle="Mispricing −25 or worse" rows={movers.overheated} metric="d30" accent="down" viewAllHref="/board?tag=overheated&sort=misAsc" emptyNote="Nothing deeply overheated today." />
        <MarketMoversPanel title="Blue Chips" subtitle="The stability shelf" rows={movers.blueChips} metric="d7" accent="neutral" viewAllHref="/board?class=blue_chip&sort=price" />
        <MarketMoversPanel title="Rookie IPOs" subtitle="First-year market debuts" rows={movers.rookieIpos} metric="d7" accent="neutral" viewAllHref="/board?class=rookie_ipo&sort=d7" />
        <MarketMoversPanel title="Most Volatile" subtitle="Highest week-to-week swing" rows={movers.mostVolatile} metric="d7" accent="neutral" viewAllHref="/board?sort=vol" />
        <MarketMoversPanel title="Most Stable" subtitle="Lowest volatility" rows={movers.mostStable} metric="d7" accent="neutral" viewAllHref="/board?sort=vol" />
      </div>

      <div className="rounded-card border border-border-subtle bg-surface p-4 text-center text-sm text-text-secondary">
        Every value on this page is generated by our market engine from simulated inputs.{' '}
        <Link to="/methodology" className="text-secondary hover:underline">
          See exactly how prices are computed →
        </Link>
      </div>

      <Footer />
    </div>
  );
}
