import { Link } from 'react-router-dom';
import { useBoard, useMarketStatus, useMovers } from '@/hooks/useMarketData';
import { useAppStore } from '@/store/useAppStore';
import { FORMATS } from '@/config/market';
import { fmtDate } from '@/lib/format';
import { Tape } from '@/components/market/Tape';
import { MarketMoversPanel } from '@/components/market/rows';
import { FormatRibbon } from '@/components/chrome/FormatRibbon';
import { DataFreshnessBadge, ConfidencePill } from '@/components/chrome/Honesty';
import { ErrorState, LoadingSkeleton } from '@/components/states';
import { Footer } from '@/components/chrome/Footer';
import { WatchlistStrip } from '@/components/market/WatchlistStrip';

export default function MarketPage() {
  const format = useAppStore((s) => s.format);
  const { data: status } = useMarketStatus();
  const board = useBoard(format);
  const movers = useMovers(format);

  return (
    <div className="space-y-5">
      {/* Market header — the "market open" ritual (§18.2) */}
      <header className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 text-2xl font-bold text-text-primary">
            <span className="relative flex h-2.5 w-2.5">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-up/60" />
              <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-up" />
            </span>
            Market Update
          </h1>
          <p className="text-sm text-text-secondary">
            {status?.marketDate ? `${fmtDate(status.marketDate)} · close 06:00 UTC · ` : ''}
            {FORMATS[format].label}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <ConfidencePill confidence="medium" />
          {status?.lastUpdated && <DataFreshnessBadge lastUpdated={status.lastUpdated} />}
          <FormatRibbon compact />
        </div>
      </header>

      {board.status === 'success' && board.data && <Tape rows={board.data} />}
      {board.status === 'loading' && <LoadingSkeleton className="h-12 w-full" />}

      <WatchlistStrip />

      {/* Movers grid — explicit loading / error / success lifecycle */}
      {movers.status === 'loading' && (
        <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3" aria-label="Loading movers">
          {Array.from({ length: 6 }, (_, i) => (
            <LoadingSkeleton key={i} className="h-64 w-full" />
          ))}
        </div>
      )}
      {movers.status === 'error' && (
        <ErrorState
          message="Today's market movers couldn't load."
          onRetry={movers.refetch}
        />
      )}
      {movers.status === 'success' && movers.data && (
        <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
          {/* "View all" leads to The Board, which now shows the PUBLISHED market. The demo
              engine's own concepts (mispricing, asset class, tags) have no published
              counterpart, so these links carry only filters the published board supports. */}
          <MarketMoversPanel title="Biggest Risers" subtitle="Top 24-hour gains" rows={movers.data.risers} metric="d1" accent="up" viewAllHref="/board?sort=value" />
          <MarketMoversPanel title="Biggest Fallers" subtitle="Top 24-hour drops" rows={movers.data.fallers} metric="d1" accent="down" viewAllHref="/board?sort=value" />
          <MarketMoversPanel title="Buy-Low Windows" subtitle="Undervalued after a 30-day dip" rows={movers.data.buyLow} metric="d30" accent="up" viewAllHref="/board" emptyNote="No buy-low windows in this format today." />
          <MarketMoversPanel title="Sell-High Warnings" subtitle="Overvalued after a 30-day run" rows={movers.data.sellHigh} metric="d30" accent="down" viewAllHref="/board" emptyNote="No sell-high warnings today." />
          <MarketMoversPanel title="Overheated Assets" subtitle="Mispricing −25 or worse" rows={movers.data.overheated} metric="d30" accent="down" viewAllHref="/board" emptyNote="Nothing deeply overheated today." />
          <MarketMoversPanel title="Blue Chips" subtitle="The stability shelf" rows={movers.data.blueChips} metric="d7" accent="neutral" viewAllHref="/board?sort=value" />
          <MarketMoversPanel title="Rookie IPOs" subtitle="First-year market debuts" rows={movers.data.rookieIpos} metric="d7" accent="neutral" viewAllHref="/board" />
          <MarketMoversPanel title="Most Volatile" subtitle="Highest week-to-week swing" rows={movers.data.mostVolatile} metric="d7" accent="neutral" viewAllHref="/board?sort=volatility" />
          <MarketMoversPanel title="Most Stable" subtitle="Lowest volatility" rows={movers.data.mostStable} metric="d7" accent="neutral" viewAllHref="/board?sort=volatility" />
        </div>
      )}

      <div className="space-y-1 rounded-card border border-border-subtle bg-surface p-4 text-center text-sm text-text-secondary">
        <p>
          Every value on this page is generated by our market engine from simulated inputs.{' '}
          <Link to="/methodology" className="text-secondary hover:underline">
            See exactly how prices are computed →
          </Link>
        </p>
        <p>
          For the real published market,{' '}
          <Link to="/board" className="text-secondary hover:underline">
            open The Board →
          </Link>
        </p>
      </div>

      <Footer />
    </div>
  );
}
