import { Link } from 'react-router-dom';
import {
  CONFIDENCE,
  FORMULA_VERSION,
  FUNDAMENTAL_WEIGHTS,
  MARKET_VALUE,
  MISPRICING_BANDS,
  MISPRICING_K,
  PRICE_BANDS,
  RISK_WEIGHTS,
  SF_QB_PREMIUM,
  SIGNAL_HYSTERESIS,
  SIGNAL_RULES,
} from '@/config/market';
import { useMarketStatus } from '@/hooks/useMarketData';
import { ValueDisclaimer } from '@/components/chrome/Honesty';
import { Footer } from '@/components/chrome/Footer';

// Everything here renders from the SAME config the engine uses (§40.2), so the
// documentation cannot lie about the behavior.

function Card({ id, title, children }: { id?: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="scroll-mt-24 rounded-card border border-border-subtle bg-surface p-4">
      <h2 className="mb-3 text-lg font-semibold text-text-primary">{title}</h2>
      {children}
    </section>
  );
}

export default function MethodologyPage() {
  const { data: marketStatus } = useMarketStatus();
  const sources = marketStatus?.sources ?? [];
  const dynW = FUNDAMENTAL_WEIGHTS.dynasty;
  const rdW = FUNDAMENTAL_WEIGHTS.redraft;

  return (
    <div className="space-y-4">
      <header>
        <h1 className="text-2xl font-bold text-text-primary">Methodology & Data Transparency</h1>
        <p className="mt-1 max-w-2xl text-sm text-text-secondary">
          No black box. Every price on PlayerTicker comes from a formula you can read on this page —
          the inputs, the weights, and the rules that assign every signal. Right now the market runs
          in demo mode: values are generated by our engine from simulated inputs so you can explore
          the product honestly before live data arrives.{' '}
          <span className="text-text-muted">Formula {FORMULA_VERSION}.</span>
        </p>
      </header>

      <Card id="demo" title="The Demo Market (what's simulated)">
        <p className="text-sm text-text-secondary">
          The MVP runs entirely on mock data: an authored player pool, sub-scores, and a scripted
          event calendar. A deterministic daily tick advances every player's price from a seed and
          the calendar date — so every visitor sees the same values on the same day, yesterday
          differs from today, and your watchlist deltas genuinely change. This is a working scale
          model, clearly labeled, that lets us validate the product before paying for live data.
          Nothing here is current player information.
        </p>
      </Card>

      <Card id="price" title="What the Market Price is">
        <p className="mb-3 text-sm text-text-secondary">
          A fictional 0–100 fantasy value index — not a dollar price, not a share price. It is
          relative and format-specific. Interpretive bands:
        </p>
        <Table
          head={['Band', 'Meaning']}
          rows={PRICE_BANDS.map((b) => [`${b.min}+`, b.label])}
        />
      </Card>

      <Card id="formula" title="The formula (weights)">
        <p className="mb-3 text-sm text-text-secondary">
          We compute two values per player, per format. <strong className="text-text-primary">Fundamental (Model) Value</strong> is a
          weighted blend of sub-scores, adjusted for age curve, injury and positional scarcity, then
          percentile-ranked across the pool into the 0–100 index.
        </p>
        <Table
          head={['Sub-score', 'Dynasty weight', 'Redraft weight']}
          rows={[
            ['Production', pct(dynW.production), pct(rdW.production)],
            ['Usage', pct(dynW.usage), pct(rdW.usage)],
            ['Opportunity', pct(dynW.opportunity), pct(rdW.opportunity)],
            ['Efficiency', pct(dynW.efficiency), pct(rdW.efficiency)],
            ['Role security', pct(dynW.roleSecurity), pct(rdW.roleSecurity)],
            ['Offensive environment', pct(dynW.offense), pct(rdW.offense)],
          ]}
        />
        <p className="mt-3 text-sm text-text-secondary">
          <strong className="text-text-primary">Market Value</strong> is sticky and sentiment-contaminated by design:
          <code className="mx-1 rounded bg-base px-1.5 py-0.5 font-mono text-xs text-text-primary">
            MV(t) = {MARKET_VALUE.stickiness}·MV(t−1) + {MARKET_VALUE.fundamentalPull}·Fundamental + {MARKET_VALUE.sentimentPull}·Sentiment + Catalyst
          </code>
          It drifts toward fundamentals but overshoots on hype and lags on quiet decline — which is
          exactly what makes mispricing a real, non-zero quantity. In Superflex, startable QBs
          receive a ×{SF_QB_PREMIUM} scarcity premium before ranking.
        </p>
      </Card>

      <Card id="mispricing" title="Mispricing (the two-value model)">
        <p className="text-sm text-text-secondary">
          Mispricing = clamp({MISPRICING_K} × (Model Value − Market Price), −100, +100). Positive means
          the market <em>may be</em> undervaluing the asset; negative means it <em>may be</em>
          overheated. It is always framed with confidence and "may be" language — never a promise.
        </p>
        <div className="mt-3">
          <Table head={['Score', 'Label']} rows={MISPRICING_BANDS.map((b) => [`${b.min >= 0 ? '+' : ''}${b.min}${b.min === 30 || b.min === -100 ? (b.min === 30 ? ' and up' : ' and below') : ''}`, b.label])} />
        </div>
      </Card>

      <Card id="signals" title="Signals & tags (rule table)">
        <p className="mb-3 text-sm text-text-secondary">
          Signals are rule-based from mispricing, risk, volatility and confidence — evaluated in order,
          first match wins. Each stored signal records which rule fired (<code className="rounded bg-base px-1 font-mono text-xs">ruleFired</code>) for
          auditability. A ±{SIGNAL_HYSTERESIS}-point hysteresis band prevents daily flip-flopping.
        </p>
        <Table
          head={['Rule', 'Condition', 'Signal']}
          rows={SIGNAL_RULES.map((r) => [r.id, r.description, label(r.signal)])}
        />
        <p className="mt-2 text-[11px] text-text-muted">
          Note: we evaluate Speculative Buy immediately before Buy so a low-confidence positive-mispricing
          call is honestly labeled speculative, per the product's "no fake certainty" principle.
        </p>
      </Card>

      <Card id="risk" title="Risk & volatility">
        <p className="mb-3 text-sm text-text-secondary">
          Risk is a weighted composite of six sub-risks (0–100 each). Volatility is the normalized
          standard deviation of daily price changes, blended with a structural prior so thin samples
          aren't shown as falsely calm.
        </p>
        <Table
          head={['Sub-risk', 'Weight']}
          rows={(Object.entries(RISK_WEIGHTS) as [string, number][]).map(([k, v]) => [cap(k), pct(v)])}
        />
      </Card>

      <Card id="confidence" title="Confidence & freshness">
        <p className="text-sm text-text-secondary">
          Confidence is banded Low (&lt;{CONFIDENCE.lowMax}) / Medium / High (&gt;{CONFIDENCE.highMin}).
          On the Demo Market it is globally capped at Medium — demo data never claims High confidence.
          Rookies are capped at Low until they have an NFL sample. Values older than{' '}
          {CONFIDENCE.staleMediumDays} days cap at Medium; older than {CONFIDENCE.staleLowDays} days cap
          at Low with a staleness warning.
        </p>
      </Card>

      <Card id="sources" title="Data source status">
        <Table
          head={['Source', 'Mode', 'Coverage']}
          rows={sources.map((s) => [s.label, s.mode.toUpperCase(), s.coverage])}
        />
      </Card>

      <Card id="cannot-know" title="What we can't know">
        <ul className="list-disc space-y-1 pl-5 text-sm text-text-secondary">
          <li>Practice reports, snap-count intent, and locker-room information.</li>
          <li>Coaching intentions and un-announced role changes.</li>
          <li>Future injuries and their severity.</li>
          <li>Anything a licensed live-data provider would supply — the MVP has none connected.</li>
        </ul>
        <p className="mt-3 text-sm text-text-secondary">
          The v1 weights are opinionated and versioned. Before any live launch, mispricing must pass a
          backtest (does the positive-mispricing cohort outperform?) or it loses its flagship placement.
        </p>
      </Card>

      <Card title="Not advice, not gambling">
        <ValueDisclaimer />
      </Card>

      <p className="text-center text-sm text-text-secondary">
        <Link to="/board" className="text-secondary hover:underline">Explore the Board →</Link>
      </p>

      <Footer />
    </div>
  );
}

function pct(n: number): string {
  return `${Math.round(n * 100)}%`;
}
function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
function label(sig: string): string {
  return sig.split('_').map(cap).join(' ');
}

function Table({ head, rows }: { head: string[]; rows: (string | number)[][] }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-left text-sm">
        <thead className="text-[11px] uppercase tracking-wide text-text-muted">
          <tr>
            {head.map((h) => (
              <th key={h} className="py-1.5 pr-3 font-medium">{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => (
            <tr key={i} className="border-t border-border-subtle/60">
              {r.map((c, j) => (
                <td key={j} className={j === 0 ? 'py-1.5 pr-3 text-text-primary' : 'py-1.5 pr-3 text-text-secondary'}>{c}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
