import { useState } from 'react';
import { fmtDateShort } from '@/lib/format';
import { cn } from '@/lib/ui';
import { Tooltip } from '@/components/ui/Tooltip';
import type {
  MarketCatalyst,
  MarketThesis,
  PlayerStatsGameLog,
  PlayerStatsSeason,
  RiskFactor,
} from '@/types/market';

// ---------- Catalysts timeline (§23.7) ----------
const MAG_LABEL = { minor: 'Minor', moderate: 'Moderate', major: 'Major' } as const;

export function CatalystList({ catalysts }: { catalysts: MarketCatalyst[] }) {
  const [expanded, setExpanded] = useState(false);
  const shown = expanded ? catalysts : catalysts.slice(0, 5);
  if (catalysts.length === 0)
    return <p className="text-sm text-text-muted">No catalysts on record for this player yet.</p>;
  return (
    <div>
      <ol className="space-y-3">
        {shown.map((c) => {
          const bull = c.direction === 'bullish';
          return (
            <li key={c.id} className="flex gap-3">
              <span
                className={cn('mt-0.5 shrink-0 text-sm', bull ? 'text-up' : 'text-down')}
                aria-hidden
              >
                {bull ? '▲' : '▼'}
              </span>
              <div className="min-w-0">
                <div className="flex flex-wrap items-baseline gap-x-2">
                  <span className="text-sm font-medium text-text-primary">{c.headline}</span>
                  <span className="text-[11px] text-text-muted">
                    {fmtDateShort(c.date)} · {MAG_LABEL[c.magnitude]} · {bull ? 'bullish' : 'bearish'}
                  </span>
                </div>
                <p className="text-xs text-text-secondary">{c.detail}</p>
              </div>
            </li>
          );
        })}
      </ol>
      {catalysts.length > 5 && (
        <button
          onClick={() => setExpanded((e) => !e)}
          className="mt-3 text-xs text-secondary hover:underline"
        >
          {expanded ? 'Show fewer' : `Show all ${catalysts.length} catalysts`}
        </button>
      )}
    </div>
  );
}

// ---------- Risk factors (§23) ----------
export function RiskFactorList({ factors }: { factors: RiskFactor[] }) {
  return (
    <ul className="space-y-2">
      {factors.map((f) => (
        <li key={f.type} className="flex items-start gap-2">
          <span className="mt-0.5 rounded bg-elevated px-1.5 py-0.5 font-mono text-[11px] tabnum text-warning">
            {f.score}
          </span>
          <div>
            <span className="text-sm font-medium text-text-primary">{f.headline}</span>
            <p className="text-xs text-text-secondary">{f.detail}</p>
          </div>
        </li>
      ))}
    </ul>
  );
}

// ---------- Bull / Bear cards (§23.8) ----------
export function BullBearCard({ bull, bear }: { bull: string; bear: string }) {
  return (
    <div className="grid gap-3 sm:grid-cols-2">
      <div className="rounded-card border border-up/25 bg-up/5 p-3">
        <h4 className="mb-1 flex items-center gap-1.5 text-sm font-semibold text-up">
          <span aria-hidden>▲</span> Bull case
        </h4>
        <p className="text-xs leading-relaxed text-text-secondary">{bull}</p>
      </div>
      <div className="rounded-card border border-down/25 bg-down/5 p-3">
        <h4 className="mb-1 flex items-center gap-1.5 text-sm font-semibold text-down">
          <span aria-hidden>▼</span> Bear case
        </h4>
        <p className="text-xs leading-relaxed text-text-secondary">{bear}</p>
      </div>
    </div>
  );
}

// ---------- Market thesis (§23.9) ----------
export function MarketThesisCard({ thesis }: { thesis: MarketThesis }) {
  const badge = thesis.generator === 'ai' ? 'AI-generated analysis' : 'Generated summary';
  return (
    <div className="rounded-card border border-border-subtle bg-surface p-4">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-sm font-semibold text-text-primary">Market Thesis</h3>
        <Tooltip label="Demo analysis generated by a deterministic template engine from this player's structured market data — not an LLM, and not invented.">
          <span className="rounded-full border border-warning/30 bg-warning/5 px-2 py-0.5 text-[11px] text-warning">
            {badge} · demo
          </span>
        </Tooltip>
      </div>
      <dl className="space-y-2.5 text-sm leading-relaxed">
        <ThesisRow label="Where value stands" text={thesis.valueSummary} />
        <ThesisRow label="Why it's moving" text={thesis.whyMoving} />
        <ThesisRow label="Bull case" text={thesis.bullCase} />
        <ThesisRow label="Bear case" text={thesis.bearCase} />
        <ThesisRow label="Verdict" text={thesis.verdict} emphasize />
      </dl>
    </div>
  );
}

function ThesisRow({ label, text, emphasize }: { label: string; text: string; emphasize?: boolean }) {
  return (
    <div>
      <dt className="text-[11px] uppercase tracking-wide text-text-muted">{label}</dt>
      <dd className={cn('text-text-secondary', emphasize && 'font-medium text-text-primary')}>{text}</dd>
    </div>
  );
}

// ---------- Stats snapshot + game log (§23.10) ----------
export function StatsSnapshot({
  stats,
  scoring,
}: {
  stats: PlayerStatsSeason;
  scoring: 'half' | 'ppr';
}) {
  if (stats.games === 0) {
    return (
      <p className="text-sm text-text-muted">
        No NFL sample yet — this rookie is priced on draft capital and landing spot. Stats populate
        once the season begins.
      </p>
    );
  }
  const cells: [string, string | number | undefined][] = [
    [`PPG (${scoring === 'ppr' ? 'PPR' : '½PPR'})`, stats.ppg[scoring].toFixed(1)],
    ['Games', stats.games],
    ['Snap %', stats.snapPct != null ? `${stats.snapPct}%` : '—'],
    [stats.carryShare != null ? 'Carry share' : 'Target share', (stats.carryShare ?? stats.targetShare) != null ? `${stats.carryShare ?? stats.targetShare}%` : '—'],
    ['Red-zone share', stats.redZoneShare != null ? `${stats.redZoneShare}%` : '—'],
    ['Total TDs', stats.totalTds ?? '—'],
  ];
  return (
    <div>
      <div className="grid grid-cols-3 gap-2">
        {cells.map(([k, v]) => (
          <div key={k} className="rounded-control border border-border-subtle bg-base px-2 py-1.5">
            <div className="text-[10px] uppercase tracking-wide text-text-muted">{k}</div>
            <div className="font-mono text-sm tabnum text-text-primary">{v}</div>
          </div>
        ))}
      </div>
      <p className="mt-2 text-[11px] text-text-muted">2025 season (demo data)</p>
    </div>
  );
}

export function GameLogTable({
  log,
  scoring,
}: {
  log: PlayerStatsGameLog[];
  scoring: 'half' | 'ppr';
}) {
  const [open, setOpen] = useState(false);
  if (log.length === 0) return null;
  return (
    <div>
      <button onClick={() => setOpen((o) => !o)} className="text-xs text-secondary hover:underline">
        {open ? 'Hide game log' : 'Show last 6 games (demo data)'}
      </button>
      {open && (
        <div className="mt-2 overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="text-[10px] uppercase tracking-wide text-text-muted">
              <tr>
                <th className="py-1 pr-2 font-medium">Wk</th>
                <th className="py-1 pr-2 font-medium">Opp</th>
                <th className="py-1 pr-2 font-medium">Line</th>
                <th className="py-1 text-right font-medium">Pts</th>
              </tr>
            </thead>
            <tbody>
              {log.map((g) => (
                <tr key={g.week} className="border-t border-border-subtle/60">
                  <td className="py-1 pr-2 font-mono tabnum text-text-secondary">{g.week}</td>
                  <td className="py-1 pr-2 text-text-secondary">{g.opponent}</td>
                  <td className="py-1 pr-2 text-text-secondary">{g.keyLine}</td>
                  <td className="py-1 text-right font-mono tabnum text-text-primary">{g.fantasyPoints[scoring].toFixed(1)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// ---------- Disabled placeholders (§20) ----------
export function SoonButton({ label }: { label: string }) {
  return (
    <Tooltip label="Coming soon — this is a P1 feature. The MVP ships the button so we can measure demand.">
      <span className="inline-flex cursor-not-allowed items-center gap-1 rounded-control border border-border-subtle px-3 py-1.5 text-sm text-text-muted opacity-70">
        {label}
        <span className="text-[10px]">soon</span>
      </span>
    </Tooltip>
  );
}
